### ISSUE TITLE
Стартовая страница

### ISSUE THREAD

**Issue by viakondratiuk** [swnsma/Rozklad#29]
Сделать так, чтобы при заходе на http://rozklad.z-tech.com.ua/ меня не редиректило на http://rozklad.z-tech.com.ua/app/signin

Сделать стартовую страницу, либо с функциональностью signin, либо с описанием проекта.
Если не заданы модуль и контроллер, то использовать дефолтные значения.

**Comment by viakondratiuk** [comment]
Почему закрыли, если меня все равно редиректит?

**Comment by konstanchuk** [comment]
треба на сайт завантажити.

**Comment by viakondratiuk** [comment]
Так сначало надо задеплоить, а потом закрывать. Потомучто я проверяю на лайве и сейчас оно не работает.
