### ISSUE TITLE
magic_object.php -> MagicObject.php

### ISSUE THREAD

**Issue by viakondratiuk** [swnsma/Rozklad#4]
Для магического объекта у нас должна быть возможность делать такие операции:
- $object->getName() - получить аттрибут
- $object->setName('Name') - сохранить аттрибут
- $object->unsName() - удалить аттрибут
- $object->hasName() - проверить наличие аттрибута

Все это реализовывать через магический метод __call($method)

public function __call($method, $args)
{
    switch (substr($method, 0, 3)) {
        case 'get' :
        ...
        case 'set' :
        ...
        ...
    }
    throw new Magic_Object_Exception('.....')

**Comment by TaniaBlindaruk** [comment]
+
